apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: argocd-vks-demo
  namespace: jason2
  labels:
    tkg-cluster-selector: argocd-vks-demo
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 192.168.156.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
    serviceDomain: cluster.local
  topology:
    class: builtin-generic-v3.3.0
    version: v1.30.8+vmware.1-fips-vkr.1
    variables:
      - name: vmClass
        value: best-effort-small
      - name: storageClass
        value: tanzu-policy
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: node-pool
          name: argocd-vks-demo-nodepool
          replicas: 1
